name: Test Runner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu
    steps:
      - name: Trust the local CA
        run: git config --global http.sslVerify false

      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Say hello
        run: echo "We're about to get down and dirty"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd
        with:
          driver: docker

      - name: Build but no push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: .
          file: Dockerfile
          push: false
          provenance: false
          tags: hello:latest
