services:

  ################################################################################
  server:
    container_name: gitea
    restart: unless-stopped
    # for podman:
    # userns_mode: keep-id
    image: docker.gitea.com/gitea:latest-rootless
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - type: bind
        bind:
          create_host_path: false
        source: ./data/git
        target: /var/lib/gitea
      - type: bind
        bind:
          create_host_path: false
        source: ./data/config
        target: /etc/gitea
      - type: bind
        bind:
          create_host_path: false
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        bind:
          create_host_path: false
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - gitea
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:2222:2222"

  ################################################################################
  db:
    container_name: gitea-db
    restart: unless-stopped
    # for podman:
    # userns_mode: keep-id
    image: oci.guero.org/postgres:latest
    env_file: .env
    volumes:
      - type: bind
        bind:
          create_host_path: false
        source: ./data/db
        target: /var/lib/postgresql/data
    networks:
      - gitea
    healthcheck:
      test: ["CMD", "/usr/local/bin/container_health.sh"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 45s

networks:
  gitea:
    external: false
    # name:
