services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--api=false"
      # - "--entrypoints.dashboard.address=:9090"
      # - "--api.dashboard=true"
      # - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/dynamic-conf"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.forwardedHeaders.trustedIPs=0.0.0.0/0"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.forwardedHeaders.trustedIPs=0.0.0.0/0"
      - "--entrypoints.websecure.http.tls.options=default@file"
      - "--certificatesresolvers.mydns.acme.dnschallenge=true"
      - "--certificatesresolvers.mydns.acme.dnschallenge.provider=namesilo"
      - "--certificatesresolvers.mydns.acme.email=user@example.org"
      - "--certificatesresolvers.mydns.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.mydns.acme.dnschallenge.propagation.delayBeforeChecks=120s"
      - "--providers.docker.network=traefik-proxy"
    # env_file: .env
    environment:
      LEGO_EXPERIMENTAL_CNAME_SUPPORT: true
      NAMESILO_API_KEY: ''
      NAMESILO_PROPAGATION_TIMEOUT: 1500
      NAMESILO_POLLING_INTERVAL: 120
      NAMESILO_TTL: 3600
    network_mode: host
    # ports:
    #   - 0.0.0.0:80:80
    #   - 0.0.0.0:443:443
    # networks:
    #   - proxy
    volumes:
      - "./letsencrypt:/letsencrypt:rw"
      # - "./certs:/etc/ssl/certs:ro"
      - "./dynamic-conf:/dynamic-conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

  whoami:
    image: "traefik/whoami:latest"
    container_name: "whoami"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.example.org`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=mydns"
      - "traefik.http.services.whoami.loadbalancer.serversTransport=upload@file"
    restart: unless-stopped

networks:
  proxy:
    external: true
    name: traefik-proxy

