services:
  musescore:
    image: oci.guero.org/musescore-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musescore
    hostname: musescore
    restart: unless-stopped
    environment:
      USER_ID : 1000
      GROUP_ID : 1000
      WEB_AUDIO : 1
      WEB_FILE_MANAGER : 1
      WEB_FILE_MANAGER_ALLOWED_PATHS : /musescore-files
      WEB_AUTHENTICATION : 0
      SECURE_CONNECTION : 0
      VNC_LISTENING_PORT : -1
      WEB_LISTENING_PORT : 5800
    networks:
      - default
    volumes:
      - type: bind
        bind:
          create_host_path: false
        source: ./files
        target: /musescore-files

networks:
  default:
    external: false
